version : '3'
services:
  sonarqube:
    image: sonarqube:alpine
    restart: always
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
