version : '3.5'
services:
  jenkins:
    restart: always
    user: jenkins
    build :
      context: .
      dockerfile: jenkins-server.Dockerfile

    ports:
      - "8050:8080"
      - "50000:50000"
    volumes:
      - jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - devops

  sonarqube:
    image: sonarqube:alpine
    restart: always
    ports:
      - "9000:9000"
      - "9002:9002"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - devops

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - ./nexus-data:/nexus-data sonatype/nexus3
    ports:
      - "9050:8081"
    networks:
      - devops

volumes:
  jenkins-volume:
    external: true


networks:
  devops:
    name: devops
    driver: bridge
